API_VERSION = "2"

Vagrant.configure(API_VERSION) do |config|
  config.vm.box = "puphpet/centos65-x64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end
